#!/bin/sh

#####################################################################
# X11/xinitrc: custom X session setup

# include common functions
. ~/.profile.d/common/common.sh

# redirect stdout and -err to logfile
exec >> ${_logdir}/xinitrc.log
exec 2>&1

# log info
echo "--------------------------------------------------------------------------------"
echo "Starting $(hostname):${0} at $(date)"

# load X resources
xrdb -merge ${_prfdir}/X11/resources

# start agents
[ -x "$(which gpg-agent)" ] && eval "$(gpg-agent --daemon)"
[ -x "$(which ssh-agent)" ] && eval "$(ssh-agent)"

echo "Environment is:"
env | sort | sed 's/^/  /'

if [ -x "$(which display)" -a -d ~/.local/share/wallpapers ]; then
    echo "Setting background image"
    export WALLPAPER=$( \
        find ~/.local/share/wallpapers -maxdepth 1 -type f | \
            sort -R | head -n1 \
    )
    display -window root ${WALLPAPER}
fi

# WM specific environment
export XDG_CURRENT_DESKTOP=GNOME

# Theming
export QT_STYLE_OVERRIDE=kvantum

# start window manager
echo "Starting window manager"
exec dbus-launch --exit-with-session \
     i3 -c "${_prfdir}/i3/config" -V >> "${_logdir}/i3.log" 2>&1
