#!/bin/sh

#####################################################################
# X11/xinitrc: custom X session setup

# include common functions
. ~/.profile.d/common/common.sh

# redirect stdout and -err to logfile
exec >> ${_logdir}/xinitrc.log
exec 2>&1

# log info
echo "--------------------------------------------------------------------------------"
echo "Starting $(hostname):${0} at $(date)"

# force encoding
export LANG="en_US.UTF-8"
export LC_ALL="${LANG}"

# load X resources
       xrdb -merge ${_prfdir}/X11/resources
try 3f xrdb -merge ${_prfdir}/X11/resources.${PROFILE_ENV}

# apply modmap
try 2f xmodmap ${_prfdir}/X11/modmap.${PROFILE_ENV}

# start agents
[ -x "$(which gpg-agent)" ]    && eval "$(gpg-agent --daemon)"
[ -x "$(which ssh-agent)" ]    && eval "$(ssh-agent)"
[ -x "$(which xscreensaver)" ] && xscreensaver -no-splash &

# custom profile
if [ -f ${_prfdir}/X11/xprofile.${PROFILE_ENV} ]; then
    . ${_prfdir}/X11/xprofile.${PROFILE_ENV}
fi

echo "Environment is:"
env | sort | sed 's/^/  /'

if [ -x "$(which xsetbg)" -a -d ~/.local/share/wallpapers ]; then
    echo "Setting background image"
    xsetbg $(find ~/.local/share/wallpapers -maxdepth 1 -type f | \
                    sort -R | head -n1)
fi

echo "Executing window manager"
try 2e exec ${_prfdir}/X11/wm.${PROFILE_ENV}
