[theme]
theme = "solarized-dark"

[icons]
icons = "awesome5"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:2) "

[[block]]
block = "cpu"
format = " $icon $utilization.eng(w:2) "
interval = 1

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "battery"
driver = "upower"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%Y-%m-%d %H:%M') "
