#!/bin/sh

. ~/.profile.d/common/common.sh

_common=${_prfdir}/i3/config
_local=${_prfdir}/i3/config.local
_custom=${_prfdir}/i3/config.${PROFILE_ENV}

cp "${_common}" "${_local}"
[ -f "${_custom}" ] && cat "${_custom}" >> "${_local}"
