#!/bin/sh

. ~/.profile.d/common/common.sh

ls ${_prfdir}/i3 | \
    sed -n "s/^workspace\.${PROFILE_ENV}\.\(0[1-9]\|10\)\.json$/\1/p" | \
while read _num; do
    # remove leading zeros
    _name=$(expr ${_num} + 0)

    # check if workspace already exists
    if i3-msg -t get_workspaces | grep -q "\"num\":${_name}"; then
        continue
    fi

    _file_name="${_prfdir}/i3/workspace.${PROFILE_ENV}.${_num}.name"
    _file_json="${_prfdir}/i3/workspace.${PROFILE_ENV}.${_num}.json"
    _file_msg="${_prfdir}/i3/workspace.${PROFILE_ENV}.${_num}.msg"

    if [ -f "${_file_name}" ]; then
        _name="${_name}: $(cat "${_file_name}")"
    fi

    i3-msg \
        "workspace ${_name}; \
         append_layout ${_file_json}; \
         $(echo $(cat ${_file_msg} 2>/dev/null))"
done
